### ISSUE TITLE
ModuleNotFoundError: No module named 'extractBootlegFeatures'

### ISSUE THREAD

**Issue by expectopatronum** [HMC-MIR/ComposerID#1]
Hi everyone,

I currently try to get started with your project and I managed to download the sheet image PDFs with the notebook `00_downloadScores.ipynb`. Very neat code!

Next I wanted to extract features using the notebook `01_extractFeatures.ipynb` but it crashes with the error `ModuleNotFoundError: No module named 'extractBootlegFeatures'`. It does not seem to be a module inside your repository. Is this something I need to install (I had some troubles with the packages listed in requirements.txt, so I might miss a package).

Your help would be appreciated. Thanks in advance!
Best regards
Verena

**Comment by expectopatronum** [comment]
I found [this](https://github.com/HMC-MIR/piano_bootleg_scores/blob/master/src/ExtractBootlegFeatures1.py) and placed it in my notebooks directory with the name `extractBootlegFeatures.py`. Now it works. Please let me know if that's not correct :)

Best regards
Verena

**Comment by dhyang33** [comment]
Hello,
Please import extractBootlegFeatures1.py instead. It has a more-updated version of the code. I will add it to the repo shortly.

**Comment by expectopatronum** [comment]
Is this a different file from the one I linked above?

**Comment by dhyang33** [comment]
Hello, Please use the code I added to the repository.

**Comment by expectopatronum** [comment]
This can't be the correct one because it doesn't contain the function `extractBootlegFeatures.processImageFile(...)`. It should probably be `processQuery` but this method has different input parameters.

**Comment by dhyang33** [comment]
Hello, Thank you for your reply. I have added the required function.
